### PR TITLE
made few changes in opsCodeInfo config element, changed UI styling fo…

### PR DESCRIPTION
**Pull request by thrinay**
…r landing page etc

### CODE REVIEW

**Comment by kebleynad** [comment]
@thrinay Please follow [this style guide](https://chris.beams.io/posts/git-commit/) for your commit messages. This makes the review a lot easier. Also, it would be nice if you could focus on describing what you've changed in the catalog entry and move the description of the changes within the components to the body of the commit message.

**Comment by thrinay** [comment]
@kebleynad Thanks for the link . Well, from now on I will be writing what has been changed in the catalog entry rather than the functionality changes in the commit message and any additional content will be written in the body of commit message 

To Summarize:
Updated frontend and config api release branches in docker-compose.yml file. 
changed version to 5.9 in rancher-compose.yml file

**Comment by kebleynad** [comment]
There are still conflicts that need to be resolved.

**Comment by thrinay** [comment]
@kebleynad Fixed the merge conflicts, please check

**Comment by thrinay** [comment]
@kebleynad I have fixed the merge conflicts from master branch. Please check

**Pull request merged**
