### PR TITLE
language flexifyer added

### PR DESCRIPTION
**Pull request by smehl**
Neuer Katalogeintrag für die Flexionskomponente im Modallogik-Projekt

### CODE REVIEW

**Comment by smehl** [comment]
the service is available in testing, not in staging. I can add these files to staging, too. However, I have to say that these branches have diverged from master quite a bit.

My approach was
1) I added a new file to testing, changed it till everything worked
2) I branched master, added these files from testing and made a pull request to the master branch

**Comment by pkaluzacog** [comment]
I know, and it sucks ;) .

for the record: the "best" (IMHO) way to do this is to create a new branch
from NEWBRANCH from master right off the start, and regularly do a "git
merge NEWBRANCH" from testing. if you're done, you can just create a PR
from NEWBRANCH to master.

2017-05-29 15:03 GMT+02:00 Sebastian Mehl <notifications@github.com>:

**Comment by smehl** [comment]
ja, fair.

btw. warum bist du pkaluzacog?

**Comment by flypenguin** [comment]
direkt ein ticket erstellt dass sich jemand mal darum kümmert. das muss
raus :D

2017-05-29 15:32 GMT+02:00 Sebastian Mehl <notifications@github.com>:

**Pull request merged**
