### PR TITLE
new version now has the demo functionality that matthias or rupprecht…

### PR DESCRIPTION
**Pull request by thrinay**
… or igor will be using and is asked to be part of configtool by the same persons. the demo features uplloading of two treatment report images and getting the cvs output result, for now all the functionality is hardcode, Just so you know :)

### CODE REVIEW

**Comment by kebleynad** [comment]
Are the production config tool instances supposed to be updated to this version including the demo features? If not this should not go into the same catalog entry to avoid accidental update of the production systems.

**Comment by thrinay** [comment]
Yes, all the production config tool instances should have this functionality. Currently there is no button or any such thing that gets to the demo view. Its the user who manually types the url to get into the demo view .

**Comment by kebleynad** [comment]
Alright :)

**Comment by kebleynad** [comment]
Please follow [this](https://chris.beams.io/posts/git-commit/) style guide for commit messages. Thanks!

**Pull request merged**
