### PR TITLE
added health-abrechnungsassistent

### PR DESCRIPTION
**Pull request by sebastianschramm**
Needed for customer demo on April 20

### CODE REVIEW

**Comment by sebastianschramm** [comment]
I insist. (Like I noted above this is for a customer demo and not a final setup)
And btw why is 16 parameters too much? How many parameters would still be ok?....

**Comment by flypenguin** [comment]
well. even 15 is bonkers. 5 would be a number I'd agree with. roundabout. the `lb_port` will be automatic in a couple of (minor, I hope) versions of Rancher.

also please don't tell me that if this is for a demo this will not stay. let's bet, okay? :)

**Comment by flypenguin** [comment]
p.s.: I not just assume this is also available in the `dev` branch. if not - please merge it in there as well. I won't delete the branch yet.

**Comment by sebastianschramm** [comment]
thank you.
I merged the commit 8726380cfb8a015e82edea8b35223dbdc8bfde4f in testing and staging

**Pull request merged**
